### ISSUE TITLE
chrome74beta client can not pub

### ISSUE THREAD

**Issue by cisco6** [open-webrtc-toolkit/owt-client-javascript#113]
publish local stream failed:  Error: Ice procedure failed.
    at t.value (owt.js:9)
    at t.value (owt.js:9)
    at C (owt.js:9)
    at owt.js:9
    at owt.js:9
    at Array.map (<anonymous>)
    at t.dispatchEvent (owt.js:9)
    at r.<anonymous> (owt.js:9)
    at r.emit (socket.io.js:6)
    at r.onevent (socket.io.js:8)
owt.js:9 Cannot find specific remote stream.
(anonymous) @ owt.js:9
C @ owt.js:9
(anonymous) @ owt.js:9
(anonymous) @ owt.js:9
dispatchEvent @ owt.js:9
(anonymous) @ owt.js:9
r.emit @ socket.io.js:6
r.onevent @ socket.io.js:8
r.onpacket @ socket.io.js:8
(anonymous) @ socket.io.js:8
r.emit @ socket.io.js:6
r.ondecoded @ socket.io.js:6
(anonymous) @ socket.io.js:8
r.emit @ socket.io.js:6
a.add @ socket.io.js:6
r.ondata @ socket.io.js:6
(anonymous) @ socket.io.js:8
r.emit @ socket.io.js:6
r.onPacket @ socket.io.js:6
(anonymous) @ socket.io.js:6
r.emit @ socket.io.js:6
r.onPacket @ socket.io.js:7
r.onData @ socket.io.js:7
ws.onmessage @ socket.io.js:8
owt.js:9 ICE connection state changed to disconnected
owt.js:9 ICE connection state changed to failed
script2.js:1914 remote stream id:  5c8fe4b6c8d9e92e9c33f697-common
2owt.js:9 Remote stream added.
owt.js:9 ICE connection state changed to checking
owt.js:9 ICE connection state changed to connected
owt.js:9 Empty candidate.

**Comment by jianjunz** [comment]
Thanks for reporting this issue. Please describe what APIs you have called and what parameters you were using.

**Comment by taste1981** [comment]
This has been fixed in latest owt-server.
