### ISSUE TITLE
grunt debug command described in README no longer exists

### ISSUE THREAD

**Issue by grgustaf** [open-webrtc-toolkit/owt-client-javascript#148]
I'm a bit confused or I would have submitted a PR to fix this myself.

The `grunt debug` target was removed in commit 2a09784.

The `peercall.html` in the `src/` tree has a <script> tag that references "../../../dist/sdk-debug/owt.js". This implies the file would need to be hosted on a webserver that includes the dist/sdk-debug tree. That is only generated by `grunt dev` currently.

But when you run `grunt` by itself, it copies the sample code into the dist subdir, copies owt.js under the js/ subdir, and patches up that <script> tag. So maybe you intend for them to run the sample from there?

Grunt also overwrites the serverAddress line in the code with https://example.com:8096, so I wanted to add some text like this to the sample README:

_After you run `grunt` in the `owt-client-javascript/scripts` directory, a modified copy of this sample will be placed the generated `owt-client-javascript/dist` directory. It might be easier to make these changes there, and host the `dist/samples/p2p` directory on the web._

One other thing to note is that in the `src/` tree version of peercall.html, the serverAddress is set to http://example.com. I wonder if it should be https://example.com:8096.

Hope that makes sense.

**Comment by jianjunz** [comment]
Hi grgustaf,

`grunt debug` has been replace by `grunt dev`. The latter one hosts a web server for debugging and evaluation.

It makes sense to set the default value of `serverAddress` to https://example.com:8096 as 8096 is default port of P2P server.
