### ISSUE TITLE
Safari mix stream subscription failed

### ISSUE THREAD

**Issue by JinChengShi** [open-webrtc-toolkit/owt-client-javascript#154]

**Comment by lzl** [comment]
I came across the same issue with `Intel_CS_WebRTC.v4.2`.

When I subscribe the mix stream on Safari, "Set remote description failed: InvalidAccessError: Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer." showed at the console panel.

![Screen Shot 2019-05-28 at 9 50 04 AM](https://user-images.githubusercontent.com/41784/59593582-c9ae3c00-9124-11e9-97ed-a35710368d58.jpg)

**Comment by buerkelr** [comment]
Hi,

I have the same error in Safari 12.1.2 (macOS 10.13.6) with Intel CS WebRTC 4.2.1 !
Is there a workaround for this issue?

Thanks.

**Comment by jianjunz** [comment]
This issue has been fixed.
