### ISSUE TITLE
Chrome browser is crashed when user publish simulcast stream with VP9 video codec

### ISSUE THREAD

**Issue by yanbin7** [open-webrtc-toolkit/owt-client-javascript#203]
Steps:
1. Create publish options:
        publishOptions = {
        audio : true,
        video:[
                            {codecPayloadType:125,rid: 'q', active: true, scaleResolutionDownBy: 4.0},
                            {codecPayloadType:125,rid: 'h', active: true, scaleResolutionDownBy: 2.0},
                            {codecPayloadType:125,rid: 'f', active: true}
                          ]
    }

2. publish local camera stream with video codec
client.publish(localStream, publishOptions,['VP9'])

Chrome browser will crash .  
Chrome version is Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by yanbin7** [comment]
![Capture](https://user-images.githubusercontent.com/1232271/63837418-0791d100-c9ae-11e9-921c-5e79a334a76b.JPG)

**Comment by yanbin7** [comment]
this issue also found if publish multi codec settings e.g  codec as ['H264','VP9']

**Comment by jianjunz** [comment]
This issue cannot be reproduce in Chrome 79.0.3906.0 (Official Build) canary (64-bit). It might be fixed.
