### ISSUE TITLE
Edge publish failed

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-client-javascript#207]
1: Edge join rom
2: Edge publish local stream to mcu 

expect : Edge publish success
actual :  Edge publish failed

use Release-v20190811ubuntu.tgz Edge publish success
use Release-v20190827ubuntu.tgz  Edge publish failed
sdp: 
o=thisisadapterortc 818006064637465 0 IN IP4 127.0.0.1^M
s=-^M
t=0 0^M
a=group:BUNDLE ^M
a=ice-options:trickle^M

**Comment by jianjunz** [comment]
Fixed.
