### ISSUE TITLE
When running nightly, I found that chrome cpu was used too much, causing mcu to report all in full load

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-client-javascript#212]
1,Environment and platform：
43mcu，ubuntu，software，chrome77
2,Reproduce step
1, running nightly
2,I found that chrome cpu was used too much, causing mcu to report all in full load
3,Result analysis
Chrome's cpu usage is too large to meet expectations

**Comment by cisco66666** [comment]
The process of pub sub deleting root is repeated more times, and the chrome process is getting larger and larger. When the chrome process reaches 500% in 8-core machines, MCU prompts "all in full load."

**Comment by cisco66666** [comment]
In contrast to chrome 75, there are no such questions

**Comment by cisco66666** [comment]
chrome-beta 77 Same as above

**Comment by jianjunz** [comment]
I cannot find any description about how Chrome crashed.

**Comment by cisco6** [comment]
> 我找不到有关Chrome崩溃的任何说明。
I don't understand what this means. What can I do for you?

**Comment by cisco66666** [comment]
already edited

**Comment by jianjunz** [comment]
Still needs more info to narrow down the cause of this issue. I have no idea about what you did in the step below.

> 1, running nightly

**Comment by cisco66666** [comment]
The October issue of nightly is normal, I think it should be updated chrome, observe for a while to see
