### ISSUE TITLE
A stop pushed stream , B haven't trigger 'ended' event

### ISSUE THREAD

**Issue by wayunge** [open-webrtc-toolkit/owt-client-javascript#214]
Operational steps：
    1. A call createToken to get valid token,A join room.
    2. B join room and pulish a atream.
    3. A publish a stream then subscribe B's forward stream.
    4. A stop A's pushed stream
Actual results:
    B haven't trigger subscribe 'ended' event
Expect:
    After stop A's pushed stream,B should trigger subscribe 'ended' event

**Comment by starwarfan** [comment]
#267

**Comment by wayunge** [comment]
Verified
Browser version: chrome 77
mcu version: mcu-all-bin-v20191011.tgz
