### ISSUE TITLE
Firefox only show single resolution for simulcast stream which published by Chrome browser

### ISSUE THREAD

**Issue by yanbin7** [open-webrtc-toolkit/owt-client-javascript#218]
Steps
1. Use Chrome browser to publish simulcast stream with codec as VP8 , resolution is 1280x720
publish option is
        publishOptions = {
        audio : true,
        video : [
         {codecPayloadType:125,rid: 'h', active: true, scaleResolutionDownBy: 2.0},
         {codecPayloadType:125,rid: 'f', active: true}
         ]}
2. Check the webrtc-internals and Chrome console , make sure the simulcast stream published successful.  Check settings for corresponding remote stream ,there is two resolution : 1280x720 and 640x360

3. Use Firefox to login and try to subscribe the stream published by Chrome in step1.
There is only single resolution for this remote stream .

​
settings: {…}
​​​​​
audio: Array [ {…} ]
​​​​​
video: (1) […]
​​​​​​
0: {…}
​​​​​​​
bitrate: NaN
​​​​​​​
codec: Object { name: "vp8", profile: undefined }
​​​​​​​
frameRate: 30
​​​​​​​
keyFrameInterval: undefined
​​​​​​​
resolution: Object { width: 640, height: 360 }
​​​​​​​
rid: undefined
​​​​​​​
<prototype>: Object { … }
​​​​​​
length: 1
​​​​​​
<prototype>: Array []
​​​​​
<prototype>: Object { … }
​​​​
source: Object { audio: "mic", video: "camera" }
​​​​
<prototype>: Object { … }
​
<prototype>: {…

**Comment by jianjunz** [comment]
Will be fixed by https://github.com/open-webrtc-toolkit/owt-server/pull/231.
