### ISSUE TITLE
Only the first simulcast stream has frame rate value

### ISSUE THREAD

**Issue by yanbin7** [open-webrtc-toolkit/owt-client-javascript#219]
Steps
1. Use Chrome browser to publish simulcast stream , codec is vp8 and resolution is 1280x720
publish option is
        publishOptions = {
        audio : true,
        video : [
         {codecPayloadType:125,rid: 'h', active: true, scaleResolutionDownBy: 2.0},
         {codecPayloadType:125,rid: 'f', active: true}
         ]
}
2. Check the corresponding remote stream , there is two sub stream , only the first stream has frame rate value.
video: Array(2)
0: e
bitrate: NaN
codec: e {name: "vp8", profile: undefined}
frameRate: 30
keyFrameInterval: undefined
resolution: e {width: 640, height: 360}
rid: undefined
__proto__: Object
1: e
bitrate: NaN
codec: e {name: "vp8", profile: undefined}
frameRate: undefined
keyFrameInterval: undefined
resolution: e {width: 1280, height: 720}
rid: undefined
__proto__: Object

**Comment by starwarfan** [comment]
server side bug

**Comment by starwarfan** [comment]
Fixed server  issue @jianjunz
