### ISSUE TITLE
Some events in JS are not displayed

### ISSUE THREAD

**Issue by GaoMingKai** [open-webrtc-toolkit/owt-client-javascript#222]
steps:
1、chrome connect server
2、user pub stream
3、user sub mix stream
4、close chrome network
Publication.ended ,
Publication.error,
Subscription.ended,
Subscription.error,
remoteForwardStream.ended
not found!

**Comment by starwarfan** [comment]
#267 remoteForwardStream.ended is not expected to trigger

**Comment by wayunge** [comment]
Already connection latest bug  [new address](https://github.com/open-webrtc-toolkit/owt-client-javascript/issues/279)
