### ISSUE TITLE
 The resolution button order of the stream of sample page sub does not meet expectations

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-client-javascript#231]
1,Environment and platform：
43mcu，ubuntu，software，chrome77
2,Reproduce step
1,Go to https://localhost:3004
2,Observe the order of the resolution buttons
3,Result analysis
The order of the buttons does not meet expectations

**Comment by jianjunz** [comment]
Please describe the issue in detail. What's expected?

**Comment by cisco66666** [comment]
Expected resolution button sorting is normal, now the order is a bit confused

**Comment by jianjunz** [comment]
I think this issue has been fixed by @starwarfan?

**Comment by GaoMingKai** [comment]
Verified bugs still exist
