### ISSUE TITLE
Can't subscribe simulcast stream if rid value and other settings e.g codec is incompatibility

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-client-javascript#236]
In document：
<nullable> rid :number
Restriction identifier to identify the RTP Streams within an RTP session. When rid is specified, other constraints will be ignored.
1. Pub a sumulcast stream.

2 sub step sumulcast flow, setting rid parameters, can not be normal sub

chrome log：
owt.js:9 Set local description failed. Message: {"stack":"Error: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local offer sdp: Failed to set local video description recv parameters."}

**Comment by starwarfan** [comment]
#248
