### ISSUE TITLE
[Regression]-simulcast sub issues

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-client-javascript#237]
1,pub a stream      video : [
         {"rid": 'q', active: true},
         {"rid": 'h', active: true}
         ]
2,remotestream.setting  have    “vp8,320x180” ，“vp8,1280x720”
3,sub    “vp8,1280x720”   failed  
subscribe failed: Target video stream does NOT satisfy:Resolution is not acceptable
logs/portal.stdout:2019-09-11 14:35:27.890  - ERROR: V11Client - unsubscribe failed: Invalid subscription id

4,sub  "vp8  320x180"   success

**Comment by starwarfan** [comment]
Fixed server issue @jianjunz
