### ISSUE TITLE
recorded stream's video codec is different from initially set stream codec

### ISSUE THREAD

**Issue by wayunge** [open-webrtc-toolkit/owt-client-javascript#238]
Operation steps:
    1. User A join room and publish stream
    2. record a stream with set video codec to h246B or h264M or h264H, set audio codec to 
        (puma...) 
    3. record a stream
Result:
    Whatever one of h264B and h164M and h264H user choose , the stream user get is with video codec h264 (Constrained Baseline)

Expect:
    the stream user  get should be the same as what user's choose

**Comment by starwarfan** [comment]
Expected server behaviour @jianjunz

**Comment by jianjunz** [comment]
Close this issue because recording is not a feature of JavaScript SDK.
