### ISSUE TITLE
Pub a shared screen and found that maxbitrate is not working

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-client-javascript#239]
1,Environment and platform：
43mcu，ubuntu，software，chrome77
2,Reproduce step
1,create screen stream
2,pub screen stream with  video maxBitrate is 500 
3,Result analysis
remotestream  video  bitrate not Expect

**Comment by jianjunz** [comment]
Publishing a desktop sharing stream with `{video:[{codec:{name: 'h264'}, maxBitrate:300}]}`. It's closed to 300kbps.
<img width="323" alt="Screen Shot 2019-10-17 at 10 14 39 AM" src="https://user-images.githubusercontent.com/2958054/66972465-46e3c080-f0c7-11e9-85dc-f5255302ad57.png">

**Comment by cisco66666** [comment]
@jianjunz Thank you jianjun's reply, I can only see the maximum 40kpbs in the picture?

**Comment by jianjunz** [comment]
It's about 40k **bytes** per second.

**Comment by cisco66666** [comment]
@jianjunz The maxbitrate set is 300kpbs. Does it mean that the maximum value in the graph is expected to be 300kpbs?

**Comment by jianjunz** [comment]
Closing this issue as there is no more information about what is going wrong.
