### ISSUE TITLE
Safari subscribe stream  failed

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-client-javascript#247]
1 safari join room
2: safari publish local stream success
3: safari subscribe mix stream will failed 

mcu version: Release-v20190914(ubuntu)

error log :
Set remote description failed: InvalidAccessError: Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.

**Comment by jianjunz** [comment]
I guess it's caused by #234.

**Comment by zhangyihui1** [comment]
verify ok with Release-v20190922
