### ISSUE TITLE
 Pub two vp8 and h264 simulcast streams, found that sub h264 simulcast stream failed

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-client-javascript#250]
1,Environment and platform：
43mcu，ubuntu，software，chrome77
2,Reproduce step
1,Pub a vp8 simulcast stream
2,Pub a h264 simulcast stream
3,Sub a simulcast stream in step 2
3,Result analysis
Sub does not return any data, the stream is black screen

**Comment by cisco66666** [comment]
1,pub share screening stream and vp8,vp9,h264 simucast stream with 1080p
2,sub h264 rid f,not date

**Comment by starwarfan** [comment]
need verify

**Comment by cisco66666** [comment]
verify
