### ISSUE TITLE
 Pub with four resolutions of simulcast stream some behaviors can not meet expectations

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-client-javascript#252]
1,Environment and platform：
43mcu，ubuntu，software，chrome77
2,Reproduce step
1，pub 720p simulcast stream with VP9
  options = {
        audio : true,
        video : [
         {rid: 'w', active: true, scaleResolutionDownBy: 6.0},
         {rid: 'q', active: true, scaleResolutionDownBy: 4.0},
         {rid: 'h', active: true, scaleResolutionDownBy: 2.0},
         {rid: 'f', active: true}
]}
2,sub rid  Only w has one stream 213x120
3,Result analysis
Rid and resolution did not meet expectations

**Comment by cisco66666** [comment]
2,pub 720p simulcast stream with VP8 H264
options = {
audio : true,
video : [
{rid: 'w', active: true, scaleResolutionDownBy: 6.0},
{rid: 'q', active: true, scaleResolutionDownBy: 4.0},
{rid: 'h', active: true, scaleResolutionDownBy: 2.0},
{rid: 'f', active: true}
]}
2,sub rid Only w，q，h has three stream   ，Subh finds sub's streamer tonnes or no data

**Comment by cisco66666** [comment]
3,pub hd1080p simulcast stream with VP8 H264
options = {
audio : true,
video : [
{rid: 'w', active: true, scaleResolutionDownBy: 6.0},
{rid: 'q', active: true, scaleResolutionDownBy: 4.0},
{rid: 'h', active: true, scaleResolutionDownBy: 2.0},
{rid: 'f', active: true}
]}
2,sub rid Only w，q，h has three stream

**Comment by cisco66666** [comment]
1，pub vga simulcast stream with VP8 h264
options = {
audio : true,
video : [
{rid: 'w', active: true, scaleResolutionDownBy: 6.0},
{rid: 'q', active: true, scaleResolutionDownBy: 4.0},
{rid: 'h', active: true, scaleResolutionDownBy: 2.0},
{rid: 'f', active: true}
]}
2,sub rid Only w and q has two stream 106x80 120x160

**Comment by cisco66666** [comment]
1，pub vga simulcast stream with VP9
options = {
audio : true,
video : [
{rid: 'w', active: true, scaleResolutionDownBy: 6.0},
{rid: 'q', active: true, scaleResolutionDownBy: 4.0},
{rid: 'h', active: true, scaleResolutionDownBy: 2.0},
{rid: 'f', active: true}
]}
2,sub rid Only w has one stream 106x80

**Comment by cisco66666** [comment]
1，pub hd1080p simulcast stream with VP8 h264
options = {
audio : true,
video : [
{rid: 'w', active: true, scaleResolutionDownBy: 6.0},
{rid: 'q', active: true, scaleResolutionDownBy: 4.0},
{rid: 'h', active: true, scaleResolutionDownBy: 2.0},
{rid: 'f', active: true}
]}
2,sub rid Only w and q,h has three stream no f,1980x1080

**Comment by lzhai** [comment]
Don't target 4 resolutions simulcast cases.
