### ISSUE TITLE
sub simulcast set framerate error

### ISSUE THREAD

**Issue by GaoMingKai** [open-webrtc-toolkit/owt-client-javascript#254]
os : ubuntu18.04
mcu : Release-v20190917ubuntu.tgz

1、pub 1080p simulcast stream with VP8
options = {
audio : true,
video : [
{rid: 'w', active: true, scaleResolutionDownBy: 6.0},
{rid: 'q', active: true, scaleResolutionDownBy: 4.0},
{rid: 'h', active: true, scaleResolutionDownBy: 2.0},
{rid: 'f', active: true}
]}
2、sub audio and video codec vp8 ,resolution set 480x270 or 960x540 ,framerate set 30 ,not set rid
error:
 sub will fail,console log error.

**Comment by jianjunz** [comment]
Fixed at server side.

**Comment by GaoMingKai** [comment]
os : ubuntu18.04
mcu : Release-v20191007ubuntu.tgz

1、pub 360p simulcast stream with VP8
options = {
audio : true,
video : [
{rid: 'h', active: true, scaleResolutionDownBy: 2.0},
{rid: 'f', active: true, scaleResolutionDownBy: 1.0}
]}
2、sub audio codec pcmu and video codec vp8 ,resolution set 640x360,framerate set 30
result:
  subscribe fail
console log:
![image](https://user-images.githubusercontent.com/20278910/66457498-230af400-eaa3-11e9-8f3c-9c002c2ca987.png)
