### ISSUE TITLE
pub simulcast issues with one streams

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-client-javascript#257]
1，pub vga  1080p  720p simulcast stream with vp9 vp8 h264
options = {
audio : true,
video : [
{rid: 'h', active: true, scaleResolutionDownBy: 2.0},
]}
2,sub rid ,       rid=undefind
and   trancecoding

**Comment by lzhai** [comment]
One rid will not trigger simulcast.
