### ISSUE TITLE
Pub a shared screen of three simulcast streams results in incorrect resolution

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-client-javascript#258]
1,Environment and platform：
43mcu，ubuntu，software，chrome77
2,Reproduce step
        1，pub 1080p simulcast share screening stream with VP8
options = {
audio : true,
video : [
{rid: 'q', active: true, scaleResolutionDownBy: 4.0},
{rid: 'h', active: true, scaleResolutionDownBy: 2.0},
{rid: 'f', active: true}
]}
        2,sub rid h q f  stream --resolution 341x192,682x384,1364x768
3,Result analysis
Sub return resolution maximum value is expected to be hd1080p

**Comment by cisco66666** [comment]
1，pub 1080 simulcast stream with VP9
options = {
audio : true,
video : [
{rid: 'q', active: true, scaleResolutionDownBy: 4.0},
{rid: 'h', active: true, scaleResolutionDownBy: 2.0},
{rid: 'f', active: true}
]}
2,sub rid Only w has one stream 341x192

**Comment by lzhai** [comment]
Incorrect test case, don't test screen sharing with simulcast.
