### ISSUE TITLE
subscribe a stream has mosaic in chrome 78 beta

### ISSUE THREAD

**Issue by wayunge** [open-webrtc-toolkit/owt-client-javascript#261]
steps:
    (centos software)
    1. user join room and subscribe a forward stream A in chrome beta
results:
    stream A has mosaic both in forward and mix
expect:
    stream A should play well both in mix and forward

**Comment by lzhai** [comment]
Can't reproduced.

**Comment by wayunge** [comment]
Verified
Browser: chrome beta 78.0.3904.50
Version: mcu-all-bin-v20191011.tgz
