### ISSUE TITLE
 The first ten seconds resolution of the pub does not reach the expected resolution

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-client-javascript#262]
1,Environment and platform：
   43mcu，ubuntu，software，chrome77
2,Reproduce step
Pub a stream of 1080p    ------vp8 and pcmu
3,Result analysis
observe the resolution of this stream after pub, found that the resolution rose to 1440x810 in about ten seconds, expecting pub immediately after 1080p
![image](https://user-images.githubusercontent.com/52657199/65737327-b8f06780-e110-11e9-8cff-eb807d015d2f.png)

**Comment by jianjunz** [comment]
It sounds like a reasonable behavior. If the start bitrate is not enough for a 1080p video, it could downgrade to a lower resolution to avid congestion.

**Comment by lzhai** [comment]
@cisco66666 Double check max bitrate setting for this 1080p case, why only 800k?

**Comment by cisco66666** [comment]
/home/webrtc/Pictures/Screenshot from 2019-09-29 16-29-57.png
As shown above, the right side is the filtered information in publication.getStats.
Found that pub does not specify MAXbitrate,
The picture is around 760, and occasionally about 2M. After a period of time, sometimes it is 1440x810, very few is 1920x1080;
/home/webrtc/Pictures/Screenshot from 2019-09-29 16-34-16.png

**Comment by jianjunz** [comment]
Cannot reproduce this issue. Encoding resolution is pretty stable on my machine.
![Capture](https://user-images.githubusercontent.com/2958054/65843256-49be8180-e363-11e9-9405-e5aecd87ecfb.PNG)

**Comment by lzhai** [comment]
With Codec VP8

**Comment by jianjunz** [comment]
> It sounds like a reasonable behavior. If the start bitrate is not enough for a 1080p video, it could downgrade to a lower resolution to avid congestion.

With VP8, I saw the resolution increased to 1080p in about 10 seconds. I think it makes sense.

**Comment by cisco66666** [comment]
Compared with vp9 and h264, the resolution is not increased to the peak after 10 seconds. This behavior is inconsistent with vp8. Is it expected?

**Comment by lzhai** [comment]
Raise to 1080p in about 10 second according to device and network condition, it make sense.
