### ISSUE TITLE
use chrome beta to visit MCU will be crash

### ISSUE THREAD

**Issue by GaoMingKai** [open-webrtc-toolkit/owt-client-javascript#263]
os : centos7.6
release version : mcu-all-bin-v20190925.tgz
chrome beta version : 78.0.39
steps:
open mcu in chrome beta,wait some seconds will be crash

picture log:
![image](https://user-images.githubusercontent.com/20278910/65668676-b7716180-e074-11e9-9d52-85e4ef30a6a9.png)

**Comment by taste1981** [comment]
Tried this in lab. The same host will event crash on getUserMedia call. Not an webrtc issue. Suggest closing it.

**Comment by GaoMingKai** [comment]
To verify
