### ISSUE TITLE
Check woogeen_video or woogeen_audio whether killed after all user left,such process didn't subtract one.

### ISSUE THREAD

**Issue by wayunge** [open-webrtc-toolkit/owt-client-javascript#266]
environment：ubuntu software
step:
1. Start mcu server
2. User join room and publish camera stream. 
3. User unpublish local strema and leave room

results:
    use command (ps -ef | grep 'workingNode video') or (command ps -ef | grep 'workingNode video') check the process
    after step2, such process will add one. it is 3
    after step3, such process didn't subtract one. it is still 3
    
expect:
 after step3,such process will subtract one

**Comment by jianjunz** [comment]
Closing this issue because it doesn't show anything wrong in JavaScript SDK.

**Comment by wayunge** [comment]
Verified,After user unpublish local stream and leave room,such process will subtract one after a few seconds.
Version:Release-v20191011ubuntu.tgz
