### ISSUE TITLE
Recorded  mix stream's video codec is different from setting video codec

### ISSUE THREAD

**Issue by wayunge** [open-webrtc-toolkit/owt-client-javascript#270]
environment:
sysytem: ubuntu software and centos software
any browser
mcu: Newest

step:
1. user join room,and publish a stream
2. user subscribe a mix stream
3. record a stream with set video codec to  'h264-B'
4.use ffprobe to check recorded file profile align with setting value

result:
 Video: h264 (Constrained Baseline)
expect:
Recorded  mix stream's video codec is should be  the starting set video codec

**Comment by jianjunz** [comment]
Closing this issue because recording is not in the scope of JavaScript SDK.

**Comment by wayunge** [comment]
Verified,Because recording is not in the scope of JavaScript SDK,It's already in owt-server
