### ISSUE TITLE
conference: Safari can not trigger publication.ended event after call publication.stop()

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-client-javascript#276]
1 safari join room
2: safari publish localStream to mcu
3: safari call publication.stop()
4: check safari publication.ended event

expect: safari should be trigger publication.ended event after call publication.stop()
actual:  safari can not  trigger publication.ended event after call publication.stop()

os:
safari: 13.0.2, macOS (10.15)

**Comment by GaoMingKai** [comment]
To verify that the bug still exists

**Comment by jianjunz** [comment]
It seems that Safari doesn't fire `iceConnectionStateChange` or `connectionStateChange` event after `PeerConnection.close` is called.

**Comment by jianjunz** [comment]
After reading the [spec](https://w3c.github.io/webrtc-pc/#update-the-ice-connection-state), Safari's behavior seems to be correct.

**Comment by yanbin7** [comment]
Please update documents
