### ISSUE TITLE
Updated event don't trigger 

### ISSUE THREAD

**Issue by GaoMingKai** [open-webrtc-toolkit/owt-client-javascript#277]
os : ubuntu
release : Release-v20191010
client : chrome , firefox, safari
**Scenario:**
   1、close user1 network(use2 check left event)
   2、close mcu network
   3、publish stream to mcu
   4、vad change
   5、resolution change
   6、pause forward stream
   7、play forward stream
   8、pulication mute 
   9、publication unmute
   10、delete remote stream
   11、drop participant(other)
**result:**
  All above 11 types of operations didn't trigger remoteStream.update event.

**Comment by lzhai** [comment]
@GaoMingKai  Step2 close MCU network, how can further events be triggered?

**Comment by GaoMingKai** [comment]
Steps close MCU network not need restart ,will be triggered (conference.serverdisconnected,publication.ended,publication.error,subscription.ended,subscription.error,remoteStream.ended,remoteStream.layoutchange,remoteStream.update(mix stream)),but remoteStream.update(mix stream) not to be triggered.

**Comment by lzhai** [comment]
Duplicate with issue #279
