### ISSUE TITLE
Pub a vp8 simulcast stream with safari, remotestream.rid does not meet expectations

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-client-javascript#295]
1,Environment and platform：
43mcu，ubuntu，software，safari
2,Reproduce step
1，pub 720p simulcast stream with vp8
options = {
audio : true,
video : [
{rid: 'h', active: true, scaleResolutionDownBy: 2.0},
{rid: 'f', active: true，scaleResolutionDownBy: 1.0}
]}
2,remotestream.setting.video.rid==="3785307925"
![image](https://user-images.githubusercontent.com/52657199/67061938-6ac10800-f194-11e9-92ba-300f54ce933e.png)

3,Result analysis
remotestream.setting.video.rid==="3785307925"

**Comment by yanbin7** [comment]
Close the bug. The document related PR has been merged.
