### ISSUE TITLE
Can't subscribe stream with video codec h264- in Firefox dev 71.0b3

### ISSUE THREAD

**Issue by wayunge** [open-webrtc-toolkit/owt-client-javascript#306]
computer: yuewanx6
browser: firefox dev 71.0b3
Step:
1、user A publish stream with any video codec
2、user B subscribe stream with video codec **(h246-B,h246-M,h246-H,h246-B,h246-CB) in firefox developer
Result:
show a green stream,have nothing
Expect:
user can subscribe stream with  video codec (h246-B,h246-M,h246-H,h246-B,h246-CB)
![image](https://user-images.githubusercontent.com/47023511/67474749-9443cd00-f687-11e9-895b-74939ef58a4e.png)

**Comment by yanbin7** [comment]
This bug can't reproduce in my laptop.

**Comment by yanbin7** [comment]
It also can't reproduce in beta version. Close the bug .
