### ISSUE TITLE
"grunt debug" not work!

### ISSUE THREAD

**Issue by linewei** [open-webrtc-toolkit/owt-client-javascript#319]
scripts# grunt debug
Warning: Task "debug" not found. Use --force to continue.

Aborted due to warnings.

scripts# grunt debug --force
Warning: Task "debug" not found. Used --force, continuing.

Done, but with warnings.

**Comment by jianjunz** [comment]
`grunt debug` has been replace by `grunt dev`.  The latter one hosts a web server for debugging and evaluation.

I would like to re-enable `grunt debug` to generate a debug version SDK without hosting a web server, so it is not removed from readme.

Duplicates #148.
