### ISSUE TITLE
after ICE Connection state goes "Failed/Closed", auto reconnection not happening

### ISSUE THREAD

**Issue by MrSmith87** [open-webrtc-toolkit/owt-client-javascript#327]
Hi Guys,
I noticed that in Android SDK, after ICE connection fails due to network connectivity issue, the client reconnects (using 'relogin' socket event) when the network is re-established and both the publication and subscription resumes.
However the same is not happening in Javascript SDK, though 'relogin' is still fired from the client and getting "ok" in return.

**Comment by jianjunz** [comment]
There are two channels need to be reconnected, socket.io signaling and ICE. The `relogin` request tries to reconnect Socket.IO channel. However, publications and subscriptions cannot resume if ICE failed to reconnect.

**Comment by MrSmith87** [comment]
ok. so, if ICE connection fails I need to rejoin the conference and re-initiate the publication and subscription. right?

**Comment by jianjunz** [comment]
You don't need to rejoin the conference if signaling channel is successfully reconnected. `ended` event of `Publication` and `Subscription` indicates there is no future attempts will be performed to recovery it. In that case, please re-initiate the publication or subscription if you still need it.

**Comment by MrSmith87** [comment]
Got it. Thanks.

**Comment by jayaramsmsc** [comment]
Hi @jianjunz , 
I observed one thing. Subscription ended event is not triggering, instead of that stream "ended" and subscription "error" event are getting triggered. I am using v4.2.1 JS SDK
