### ISSUE TITLE
Cannot publish an Audio-only Stream

### ISSUE THREAD

**Issue by MrSmith87** [open-webrtc-toolkit/owt-client-javascript#349]
Video Call works fine using MCU v4.3.
On Video Pause, I am capturing an audio-only stream using getUserMedia and publishing the same. I am getting an error while creating Owt.Base.LocalStream object as follows 

localStream = new Owt.Base.LocalStream(myStream, new Owt.Base.StreamSourceInfo('mic', undefined), attr);

Error : TypeError: Missing audio source info or video source info.

However document says this :
Audio source info or video source info could be undefined if a stream does not have audio/video track. Video source info : Accepted values are: "camera", "screen-cast", "file", "mixed" or undefined.

So, I guess this is a bug.

Please help, kind of stuck!

**Comment by MrSmith87** [comment]
Hi Guys,
I would really appreciate a response to this as I am totally stuck.
Thanks in anticipation.

Sumit

**Comment by jianjunz** [comment]
Hi Sumit,

Please check the MediaStream you created. If it has one or more video tracks, but no video source is provided, you'll see the error above.

**Comment by MrSmith87** [comment]
Hi,

Thanks a lot. My bad, working fine now. Issue was with my code.

One query - 

Currently, whenever I pause the video, I stop the existing publication, doing a fresh getUserMedia with audio-only constraints and publish the new stream.
 Is there a way I can just replace the media track in the peer connection object via your function so that I don't have to publish the new stream?

**Comment by jianjunz** [comment]
Hi Sumit,

It's not supported right now, unless you modify the SDK code. But it'll be possible to replace track when #317 is implemented.

**Comment by MrSmith87** [comment]
Got it. thanks.
