### ISSUE TITLE
Stream subscription not working without media devices permission.

### ISSUE THREAD

**Issue by kurapatijayaram** [open-webrtc-toolkit/owt-client-javascript#376]
Hi,
I am using v4.2.1 . I am unable to subscribe to a stream without media device permission (camera, mic). I dont know the reason behind this. Even in sample application, when I tried with "publish=false" to check the streams in the room, even then it didnt worked. Can someone help me on this.

Thank you.

**Comment by jianjunz** [comment]
It seems to be an ICE issue at server side. It's expected to be fixed in master.

**Comment by kurapatijayaram** [comment]
Thanks @jianjunz for the reply, we are waiting for the fix.

**Comment by jianjunz** [comment]
You can try the master branch of OWT server. It's assumed to be fixed there.

**Comment by kurapatijayaram** [comment]
How stable is the current master version ? 
Can you pls confirm whether this fix exists in master branch or not ?

Thank you.

**Comment by kurapatijayaram** [comment]
@jianjunz can you pls reply on this.

Thank you.

**Comment by kurapatijayaram** [comment]
Its working fine with latest version v4.3.1 .

thank you.
