### ISSUE TITLE
Auto mixing available ?

### ISSUE THREAD

**Issue by kurapatijayaram** [open-webrtc-toolkit/owt-client-javascript#379]
Hi,
I just want to know, is there any way to start mixing streams automatically ? like at the time of publishing the stream or any option while creating the room ?

Thank you.

**Comment by jianjunz** [comment]
Hi kurapatijayaram,

There is no mix API provided in JavaScript SDK. Please consider REST APIs provided by the server.

**Comment by kurapatijayaram** [comment]
At room level can we configure ??

**Comment by jianjunz** [comment]
This is out of the scope of JavaScript SDK. Please find support from server side. Thanks.

**Comment by kurapatijayaram** [comment]
Thank you @jianjunz
