### ISSUE TITLE
Safari 13.1.1 it doesn't work

### ISSUE THREAD

**Issue by Geekhyt** [open-webrtc-toolkit/owt-client-javascript#388]
It can be used normally in Safari 13.0, but 13.1.1 will not work. I tried to read the source code and Safari's release notes, but I didn't find the reason.

**Comment by jianjunz** [comment]
Hi,

Please describe the steps to reproduce your issue. What's expected and what's actually happened. Thanks.

**Comment by Geekhyt** [comment]
> Hi,
> 
> Please describe the steps to reproduce your issue. What's expected and what's actually happened. Thanks.

I mean, under version 13.1.1 of Safari, the use is normal, but in version 13.1.1, the console reports an error: Subscription failed. What is the reason? Moreover, in the process of debugging the source code, I found that there is no code to judge the old and new browsers of Safari. If you study the details further, you will find that in sdp, the media types of a=rtpmap sent by old and new browsers are different. sdp is the intersection of sending and receiving. Will sdp change after Safari update?

**Comment by jianjunz** [comment]
Since there is no reproduce steps, logs, versions of the product provided, it's hard for us to try and analyze this issue.

**Comment by Geekhyt** [comment]
> Since there is no reproduce steps, logs, versions of the product provided, it's hard for us to try and analyze this issue.

The latest SDK version cannot be subscribed successfully in Safari 13.1.1. The console reports an error like this:subscribe failed-Error:Ice procedure failed.You can try it in this version of Safari.

**Comment by jianjunz** [comment]
It looks like you observed this issue in conference mode. Please find detailed error information from your server's log.

**Comment by Geekhyt** [comment]
> It looks like you observed this issue in conference mode. Please find detailed error information from your server's log.

This is the server log, and no abnormalities were found.

2020-07-10 10:46:34.080  - DEBUG: Portal - participant[ b8YLm1G_KF7S0mjsAAd1 ] join with token: {"tokenId":"5f07d6899835a52113b532d7","host":"live-webrtc-server-91.csdn.net:8080","secure":true,"signature":"NTFjMjFmMjljZWFjY2Y5NjkwMTUyYWE3NjE3NTRkODAwYmU1YWY0MTZjNWY2YzY3ZDgxNDg2YjFhMWI5MmNkMQ=="}
2020-07-10 10:46:34.081  - DEBUG: Portal - token validation ok.
2020-07-10 10:46:34.082  - DEBUG: Portal - login ok. { _id: 5f07d6899835a52113b532d7,
  user: 'weixin_34920636',
  room: 5f0715992d98590867ce722c,
  role: 'presenter',
  service: 5ef9a0ee58a2954b57fa0478,
  creationDate: 2020-07-10T02:46:33.919Z,
  origin: { isp: '', region: '' },
  code: '85743163249',
  secure: true,
  host: 'live-webrtc-server-91.csdn.net:8080',
  __v: 0 }
2020-07-10 10:46:34.084  - DEBUG: Portal - got controller: conference-50fdd15ea574003e2075@172.16.130.91_61
2020-07-10 10:46:34.085  - DEBUG: Portal - join ok, result: { permission:
   { publish: { audio: true, video: true },
     subscribe: { audio: true, video: true } },
  room:
   { id: '5f0715992d98590867ce722c',
     views: [ 'common' ],
     participants: [ [Object], [Object], [Object] ],
     streams: [ [Object] ] } }
2020-07-10 10:46:34.365  - DEBUG: LoadCollector - cpu usage: 0.07692307692307687
2020-07-10 10:46:34.742  - DEBUG: Portal - publish, participantId: b8YLm1G_KF7S0mjsAAd1 streamId: 613022998511614700 pubInfo: { media:
   { audio: { source: 'mic' },
     video: { source: 'camera', parameters: [Object] } },
  type: 'webrtc' }
2020-07-10 10:46:34.774  - DEBUG: Portal - onSessionSignaling, participantId: b8YLm1G_KF7S0mjsAAd1 sessionId: 613022998511614700 signaling: { type: 'offer',
  sdp: 'v=0\r\no=- 1464792404186740665 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:STqD\r\na=ice-pwd:cS7YyDxwboqzXKRl75L/wql4\r\na=ice-options:trickle\r\na=fingerprint:sha-256 77:7D:B7:31:AC:8C:2F:88:49:DB:16:41:AA:45:55:5E:80:27:AB:C1:03:DB:25:91:7B:FB:FE:32:63:6F:E6:A2\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendonly\r\na=msid:- 1e33fcb8-1841-4bf5-89f2-1fb24c303f80\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:1832406718 cname:JxpldwsZeOK6xyEm\r\na=ssrc:1832406718 msid:- 1e33fcb8-1841-4bf5-89f2-1fb24c303f80\r\na=ssrc:1832406718 mslabel:-\r\na=ssrc:1832406718 label:1e33fcb8-1841-4bf5-89f2-1fb24c303f80\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 122 127 121 125 107 108 109 124 120 123 119 114 115 116\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:STqD\r\na=ice-pwd:cS7YyDxwboqzXKRl75L/wql4\r\na=ice-options:trickle\r\na=fingerprint:sha-256 77:7D:B7:31:AC:8C:2F:88:49:DB:16:41:AA:45:55:5E:80:27:AB:C1:03:DB:25:91:7B:FB:FE:32:63:6F:E6:A2\r\na=setup:actpass\r\na=mid:1\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:13 urn:3gpp:video-orientation\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07\r\na=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendonly\r\na=msid:- 36c95b27-c9c3-4cbe-89ce-edca638391e2\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 profile-id=0\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 VP9/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 profile-id=2\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:102 H264/90000\r\na=rtcp-fb:102 goog-remb\r\na=rtcp-fb:102 transport-cc\r\na=rtcp-fb:102 ccm fir\r\na=rtcp-fb:102 nack\r\na=rtcp-fb:102 nack pli\r\na=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:122 rtx/90000\r\na=fmtp:122 apt=102\r\na=rtpmap:127 H264/90000\r\na=rtcp-fb:127 goog-remb\r\na=rtcp-fb:127 transport-cc\r\na=rtcp-fb:127 ccm fir\r\na=rtcp-fb:127 nack\r\na=rtcp-fb:127 nack pli\r\na=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f\r\na=rtpmap:121rtx/90000\r\na=fmtp:121 apt=127\r\na=rtpmap:125 H264/90000\r\na=rtcp-fb:125 goog-remb\r\na=rtcp-fb:125 transport-cc\r\na=rtcp-fb:125 ccm fir\r\na=rtcp-fb:125 nack\r\na=rtcp-fb:125 nack pli\r\na=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:107 rtx/90000\r\na=fmtp:107 apt=125\r\na=rtpmap:108 H264/90000\r\na=rtcp-fb:108 goog-remb\r\na=rtcp-fb:108 transport-cc\r\na=rtcp-fb:108ccm fir\r\na=rtcp-fb:108 nack\r\na=rtcp-fb:108 nack pli\r\na=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f\r\na=rtpmap:109 rtx/90000\r\na=fmtp:109 apt=108\r\na=rtpmap:124 H264/90000\r\na=rtcp-fb:124 goog-remb\r\na=rtcp-fb:124 transport-cc\r\na=rtcp-fb:124 ccm fir\r\na=rtcp-fb:124 nack\r\na=rtcp-fb:124 nack pli\r\na=fmtp:124 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d0032\r\na=rtpmap:120 rtx/90000\r\na=fmtp:120 apt=124\r\na=rtpmap:123 H264/90000\r\na=rtcp-fb:123 goog-remb\r\na=rtcp-fb:123 transport-cc\r\na=rtcp-fb:123 ccm fir\r\na=rtcp-fb:123 nack\r\na=rtcp-fb:123 nack pli\r\na=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032\r\na=rtpmap:119 rtx/90000\r\na=fmtp:119 apt=123\r\na=rtpmap:114 red/90000\r\na=rtpmap:115 rtx/90000\r\na=fmtp:115 apt=114\r\na=rtpmap:116 ulpfec/90000\r\na=ssrc-group:FID 3063309194 1943675288\r\na=ssrc:3063309194 cname:JxpldwsZeOK6xyEm\r\na=ssrc:3063309194 msid:- 36c95b27-c9c3-4cbe-89ce-edca638391e2\r\na=ssrc:3063309194 mslabel:-\r\na=ssrc:3063309194 label:36c95b27-c9c3-4cbe-89ce-edca638391e2\r\na=ssrc:1943675288 cname:JxpldwsZeOK6xyEm\r\na=ssrc:1943675288 msid:- 36c95b27-c9c3-4cbe-89ce-edca638391e2\r\na=ssrc:1943675288 mslabel:-\r\na=ssrc:1943675288 label:36c95b27-c9c3-4cbe-89ce-edca638391e2\r\n' }
2020-07-10 10:46:34.819  - DEBUG: Portal - onSessionSignaling, participantId: b8YLm1G_KF7S0mjsAAd1 sessionId: 613022998511614700 signaling: { type: 'candidate',
  candidate:
   { candidate: 'a=candidate:2743663043 1 udp 2122260223 192.168.30.12 58790 typ host generation 0 ufrag STqD network-id 2',
     sdpMid: '0',
     sdpMLineIndex: 0 } }
2020-07-10 10:46:34.820  - DEBUG: Portal - onSessionSignaling, participantId: b8YLm1G_KF7S0mjsAAd1 sessionId: 613022998511614700 signaling: { type: 'candidate',
  candidate:
   { candidate: 'a=candidate:578281398 1 udp 2122194687 192.168.81.56 56389 typ host generation 0 ufrag STqD network-id 1 network-cost 10',
     sdpMid: '0',
     sdpMLineIndex: 0 } }
2020-07-10 10:46:34.821  - DEBUG: Portal - onSessionSignaling, participantId: b8YLm1G_KF7S0mjsAAd1 sessionId: 613022998511614700 signaling: { type: 'candidate',
  candidate:
   { candidate: 'a=candidate:2743663043 1 udp 2122260223 192.168.30.12 60006 typ host generation 0 ufrag STqD network-id 2',
     sdpMid: '1',
     sdpMLineIndex: 1 } }
2020-07-10 10:46:34.821  - DEBUG: Portal - onSessionSignaling, participantId: b8YLm1G_KF7S0mjsAAd1 sessionId: 613022998511614700 signaling: { type: 'candidate',
  candidate:
   { candidate: 'a=candidate:578281398 1 udp 2122194687 192.168.81.56 57344 typ host generation 0 ufrag STqD network-id 1 network-cost 10',
     sdpMid: '1',
     sdpMLineIndex: 1 } }
2020-07-10 10:46:34.865  - DEBUG: Portal - subscribe, participantId: b8YLm1G_KF7S0mjsAAd1 subscriptionId: 695924458367187300 subDesc: { media:
   { audio: { from: '613022998511614700' },
     video: { from: '613022998511614700' } },
  type: 'webrtc' }
2020-07-10 10:46:34.903  - DEBUG: Portal - onSessionSignaling, participantId: b8YLm1G_KF7S0mjsAAd1 sessionId: 695924458367187300 signaling: { type: 'offer',
  sdp: 'v=0\r\no=- 6425671602337072617 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:Zosl\r\na=ice-pwd:CAgtje0BjfR4EpjzxcQHQBdv\r\na=ice-options:trickle\r\na=fingerprint:sha-256 73:48:A6:04:15:54:6F:1E:D8:3B:C7:C7:BF:39:22:F5:2C:FD:EC:2A:1D:46:88:C5:DE:54:A6:A4:D0:00:AC:D4\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 122 127 121 125 107 108 109 124 120 123 119 114 115 116\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:Zosl\r\na=ice-pwd:CAgtje0BjfR4EpjzxcQHQBdv\r\na=ice-options:trickle\r\na=fingerprint:sha-256 73:48:A6:04:15:54:6F:1E:D8:3B:C7:C7:BF:39:22:F5:2C:FD:EC:2A:1D:46:88:C5:DE:54:A6:A4:D0:00:AC:D4\r\na=setup:actpass\r\na=mid:1\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:13 urn:3gpp:video-orientation\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07\r\na=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=recvonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 profile-id=0\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 VP9/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 profile-id=2\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:102 H264/90000\r\na=rtcp-fb:102 goog-remb\r\na=rtcp-fb:102 transport-cc\r\na=rtcp-fb:102 ccm fir\r\na=rtcp-fb:102 nack\r\na=rtcp-fb:102 nack pli\r\na=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:122 rtx/90000\r\na=fmtp:122 apt=102\r\na=rtpmap:127 H264/90000\r\na=rtcp-fb:127 goog-remb\r\na=rtcp-fb:127 transport-cc\r\na=rtcp-fb:127 ccm fir\r\na=rtcp-fb:127 nack\r\na=rtcp-fb:127 nack pli\r\na=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f\r\na=rtpmap:121 rtx/90000\r\na=fmtp:121 apt=127\r\na=rtpmap:125 H264/90000\r\na=rtcp-fb:125 goog-remb\r\na=rtcp-fb:125 transport-cc\r\na=rtcp-fb:125 ccm fir\r\na=rtcp-fb:125 nack\r\na=rtcp-fb:125 nack pli\r\na=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:107 rtx/90000\r\na=fmtp:107 apt=125\r\na=rtpmap:108 H264/90000\r\na=rtcp-fb:108 goog-remb\r\na=rtcp-fb:108 transport-cc\r\na=rtcp-fb:108 ccm fir\r\na=rtcp-fb:108 nack\r\na=rtcp-fb:108 nack pli\r\na=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f\r\na=rtpmap:109 rtx/90000\r\na=fmtp:109 apt=108\r\na=rtpmap:124 H264/90000\r\na=rtcp-fb:124 goog-remb\r\na=rtcp-fb:124 transport-cc\r\na=rtcp-fb:124 ccm fir\r\na=rtcp-fb:124 nack\r\na=rtcp-fb:124 nack pli\r\na=fmtp:124 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d0032\r\na=rtpmap:120 rtx/90000\r\na=fmtp:120 apt=124\r\na=rtpmap:123 H264/90000\r\na=rtcp-fb:123 goog-remb\r\na=rtcp-fb:123 transport-cc\r\na=rtcp-fb:123 ccmfir\r\na=rtcp-fb:123 nack\r\na=rtcp-fb:123 nack pli\r\na=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032\r\na=rtpmap:119 rtx/90000\r\na=fmtp:119 apt=123\r\na=rtpmap:114 red/90000\r\na=rtpmap:115 rtx/90000\r\na=fmtp:115 apt=114\r\na=rtpmap:116 ulpfec/90000\r\n' }
2020-07-10 10:46:34.959  - DEBUG: Portal - onSessionSignaling, participantId: b8YLm1G_KF7S0mjsAAd1 sessionId: 695924458367187300 signaling: { type: 'candidate',
  candidate:
   { candidate: 'a=candidate:2743663043 1 udp 2122260223 192.168.30.12 61229 typ host generation 0 ufrag Zosl network-id 2',
     sdpMid: '0',
     sdpMLineIndex: 0 } }
2020-07-10 10:46:34.960  - DEBUG: Portal - onSessionSignaling, participantId: b8YLm1G_KF7S0mjsAAd1 sessionId: 695924458367187300 signaling: { type: 'candidate',
  candidate:
   { candidate: 'a=candidate:578281398 1 udp 2122194687 192.168.81.56 52736 typ host generation 0 ufrag Zosl network-id 1 network-cost 10',
     sdpMid: '0',
     sdpMLineIndex: 0 } }
2020-07-10 10:46:34.961  - DEBUG: Portal - onSessionSignaling, participantId: b8YLm1G_KF7S0mjsAAd1 sessionId: 695924458367187300 signaling: { type: 'candidate',
  candidate:
   { candidate: 'a=candidate:2743663043 1 udp 2122260223 192.168.30.12 58220 typ host generation 0 ufrag Zosl network-id 2',
     sdpMid: '1',
     sdpMLineIndex: 1 } }
2020-07-10 10:46:34.961  - DEBUG: Portal - onSessionSignaling, participantId: b8YLm1G_KF7S0mjsAAd1 sessionId: 695924458367187300 signaling: { type: 'candidate',
  candidate:
   { candidate: 'a=candidate:578281398 1 udp 2122194687 192.168.81.56 60779 typ host generation 0 ufrag Zosl network-id 1 network-cost 10',
     sdpMid: '1',
     sdpMLineIndex: 1 } }

**Comment by jianjunz** [comment]
Hi,

It looks like there is no error in the log above.
