### ISSUE TITLE
the P2P samples cannot run with HTTPS port 

### ISSUE THREAD

**Issue by wynn5a** [open-webrtc-toolkit/owt-client-javascript#391]
Hello guys,
I am running the sample P2P application by following README [steps](https://github.com/open-webrtc-toolkit/owt-client-javascript/blob/master/src/samples/p2p/README.md) and serving in Nginx with https. 
But I cannot connect to HTTPS port 8096 served by Intel OWT PeerServer because certificate error. 

All certificates used in the server replaced with my self signed certificate including Nginx and PeerServer.

How to make the sample work with self signed certificate? Any help will be  appreciated.

**Comment by jianjunz** [comment]
Hi,

As you metioned, you cannot connect to secure port because of certificate error. So you need to replace it with a valid certificate.
