### ISSUE TITLE
Chorme, Edge on Desktop Windows 10 with Chromium version 85.0.4183.83 is not working in v4.3.1

### ISSUE THREAD

**Issue by hakicode** [open-webrtc-toolkit/owt-client-javascript#410]
Dear Team,

Chorme, Edge on Desktop Windows 10 with Chromium version 85.0.4183.83 is not working in v4.3.1.

I tried a new install but at version 4.3.1 it still doesn't work with Chrome, but it works with Firefox and on mobile devices (Chrome on Android, Safari on Ios)

I really need your support, because our project is working on it for clients.

Thanks!

---------------------
Gửi Team,
Chrome, Edge trên máy tính chạy hệ điều hành Windows 10 với nhân Chromium v85.0.4183.83 không hoạt động với phiên bản v4.3.1.

Tôi đã thử cài mới nhưng nó vẫn không hoạt động với Chrome, nhưng nó lại hoạt động đối với Firefox và trên các thiết bị di động (Chrome on Android, Safari on Ios)

Tôi rất cần sự hỗ trợ, bởi vì dự án của chúng tôi đang triển khai cho khách hàng.

Cám ơn tất cả!

**Comment by jianjunz** [comment]
Hi,

This is a server side issue. It has been fixed in master branch.

**Comment by hakicode** [comment]
> Hi,
> 
> This is a server side issue. It has been fixed in master branch.

Thank jianjunz.
But i am using version 4.3.1
How can I update the patch or wait for version 4.3.2

----
Cám ơn jianjunz.
Tuy nhiên tôi đang sử dụng phiên bản 4.3.1
Làm thế nào để tôi có thể cập nhật bản vá lỗi đó hay tôi phải đợi phiên bản 4.3.2

**Comment by jianjunz** [comment]
AFAIK, that fix is not included in 4.3.1. @starwarfan, could you please give a commit ID for the fix. Then you can apply the change locally.

**Comment by starwarfan** [comment]
> AFAIK, that fix is not included in 4.3.1. @starwarfan, could you please give a commit ID for the fix. Then you can apply the change locally.

https://github.com/open-webrtc-toolkit/owt-server/commit/1c453f1a3a4a2443b6a283587e59d3149e150cc4

**Comment by kurapatijayaram** [comment]
Hi, you can use latest 4.3.x branch code.
