### ISSUE TITLE
js p2p : connect p2p server fail when set useName in (undefined, null, ''" )

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-client-javascript#423]
1: chrome connect server with 
p2p.connect({
      host: serverAddress,
      token: undefined
    }).then(() => {
      $('#uid').prop('disabled', true);
    }, (error) => {
      console.log('Failed to connect to the signaling server.');
    }); // Connect to signaling server.

except:
 connect server success

actual:
  connect api trigger failure callback

**Comment by jianjunz** [comment]
Fixed by https://github.com/open-webrtc-toolkit/owt-server-p2p/pull/26.
