### ISSUE TITLE
Subscription Error event is triggering when publication is stopped.

### ISSUE THREAD

**Issue by kurapatijayaram** [open-webrtc-toolkit/owt-client-javascript#430]
Hi , 
I am using v4.3.1, when I stop my publication, both subscription ended and error events were triggered at subscriber side. This behavior should not be like this right ?  

subscription "ended" event should be triggered when publication got stopped.

Pls help me .

Thank you.

**Comment by starwarfan** [comment]
Subscription will fail if related publication is ended. It's expected behaviour.

**Comment by kurapatijayaram** [comment]
Hi @starwarfan ,
Thanks for the reply, then what is the difference between "error" and "ended" events ?

**Comment by kurapatijayaram** [comment]
Hi @yanbin7  and @starwarfan ,
When both ("error" and "ended") events are triggered when stream publication stops then what is the need of having two events ?
Can you guys please help me in this .

Thank you.
