### ISSUE TITLE
stream ended event problem

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-client-javascript#448]
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87
2，Reproduce step：
stop localstream（mediaStream.getTracks().forEach(track => {
            track.stop();
        })），There is no stream ended event after stopping the local stream
3，Expected ：
There is stream ended event after stopping the local stream

**Comment by jianjunz** [comment]
Closing this issue as `LocalStream`s don't have `ended` event. If you want to know when a `MediaStream` is ended, please add a listener to `LocalStream.stream`.
