### ISSUE TITLE
remotestream ended issue

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-client-javascript#449]
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87
2，Reproduce step：
     First scene
     1,The userA publishes a stream and calls client.leave
     2，After the above steps, user A the remotestream ended event is not triggered, and the same is true on the Android side
     two scene
     3,The userB publishes a stream and client network disconnect
     4,After the above steps, userB the remotestream ended event is not triggered, and the same is true on the Android side

3，Expected ：
the remotestream ended event is triggered

**Comment by jianjunz** [comment]
Fixed.
