### ISSUE TITLE
unit test issue

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-client-javascript#453]
1,In the file test/unit/resources/scripts/base.js, there is a problem in the following case：
'Create LocalStream with incorrect arguments should throw error.‘
2,The error of this case is as follows:
00:00:57.271  [1A[2KHeadlessChrome 0.0.0 (Linux 0.0.0) Unit tests for Stream Create LocalStream with incorrect arguments should throw error. FAILED
00:00:57.271  	AssertionError: expected [Function] to throw 'TypeError' but 'ReferenceError: SendStream is not defined' was thrown
00:00:57.271  	    at Context.<anonymous> (/tmp/test/unit/resources/scripts/base.js:145:4 <- /tmp/ae36710c76a922a6a2bd86e899c107cf.browserify:8828:16)

**Comment by jianjunz** [comment]
Fixed by #455.
