### ISSUE TITLE
Linting and Styling rules

### ISSUE THREAD

**Issue by griimick** [open-webrtc-toolkit/owt-client-javascript#528]
I am getting different result when using the eslint and jsbeautify rules mentioned in the [source here](https://github.com/open-webrtc-toolkit/owt-client-javascript/tree/main/src). Are these being used in master or there is a different config which is used? If not, can someone point me to the correct ones?

**Comment by jianjunz** [comment]
Thanks for reporting this issue. We use eslint for linting. There is a workflow to ensure all code submitted follows eslint rules.

jsbeautify was used earlier to format the code. I guess we can remove it now.

**Comment by griimick** [comment]
Does the workflow you mentioned use the same config as in this repo? If yes, please close this issue as it answers my questions. If not, can you link to the correct one. Thanks.

**Comment by jianjunz** [comment]
Yes, the config is src/.eslintrc.json.

An example of the workflow: https://github.com/open-webrtc-toolkit/owt-client-javascript/runs/4577734955?check_suite_focus=true.
