### ISSUE TITLE
Does it support H265/HEVC when p2p call?

### ISSUE THREAD

**Issue by quanqigu** [open-webrtc-toolkit/owt-client-javascript#546]
Does it support H265/HEVC when p2p call?
The features has said it support hevc. I want to know how to this?
![image](https://user-images.githubusercontent.com/80673452/164165164-19a36cd5-135e-4e4d-9f38-f2cb1ff548fe.png)

**Comment by jianjunz** [comment]
It depends on your browser. For now, only Safari supports HEVC behinds a flag.

**Comment by quanqigu** [comment]
> It depends on your browser. For now, only Safari supports HEVC behinds a flag.

OK, thanks. I got it.
