### ISSUE TITLE
Mixed stream lags in latest version's Chrome but works well in old version's.

### ISSUE THREAD

**Issue by GStarP** [open-webrtc-toolkit/owt-client-javascript#591]
Just publish and mix mic audio and screen video, after abount 3s, the subscribed mixed stream begins to lag.

However, the problem disappears in old version Chrome.

More info and a minium reproduction is here: https://github.com/GStarP/owt-chrome-issue

**Comment by starwarfan** [comment]
It may be a fixed tcc issue. You can try latest 5.0.x owt-server code to see if the problem still happens.

**Comment by GStarP** [comment]
Problem disappears when using owt-server-5.1.0, thanks.
