### ISSUE TITLE
p2p: chrome(72) call p2pClient.getStats(remoteId) and publication.getStats() can not get useful detail message.

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-client-javascript#91]
1: client1(chrome) and client2(chrome) connect server with h264
2: client1 and client2 addAllowRemoteId each other
3: client1 publish to client2
4: client1 call p2pClient.getStats(client2Id) 
expect : can get h264 in RTCStatsReport
actual : 
peercall.html:138 RTCStatsReport {size: 69}size: 69__proto__: RTCStatsReportentries: ƒ entries()arguments: (...)caller: (...)length: 0name: "entries"__proto__: ƒ ()[[Scopes]]: Scopes[0]forEach: ƒ forEach()arguments: (...)caller: (...)length: 1name: "forEach"__proto__: ƒ ()apply: ƒ apply()arguments: (...)bind: ƒ bind()call: ƒ call()caller: (...)constructor: ƒ Function()length: 0name: ""toString: ƒ toString()Symbol(Symbol.hasInstance): ƒ [Symbol.hasInstance]()get arguments: ƒ ()set arguments: ƒ ()get caller: ƒ ()set caller: ƒ ()__proto__: Object[[FunctionLocation]]: <unknown>[[Scopes]]: Scopes[0][[Scopes]]: Scopes[0]No propertiesget: ƒ ()arguments: (...)caller: (...)length: 1name: "get"__proto__: ƒ ()[[Scopes]]: Scopes[0]has: ƒ has()arguments: (...)caller: (...)length: 1name: "has"__proto__: ƒ ()[[Scopes]]: Scopes[0]keys: ƒ keys()arguments: (...)caller: (...)length: 0name: "keys"__proto__: ƒ ()apply: ƒ apply()arguments: (...)bind: ƒ bind()call: ƒ call()caller: (...)constructor: ƒ Function()length: 0name: ""toString: ƒ toString()Symbol(Symbol.hasInstance): ƒ [Symbol.hasInstance]()get arguments: ƒ ()arguments: (...)caller: (...)length: 0__proto__: ƒ ()[[Scopes]]: Scopes[0]set arguments: ƒ ()get caller: ƒ ()set caller: ƒ ()__proto__: Object[[FunctionLocation]]: <unknown>[[Scopes]]: Scopes[0][[Scopes]]: Scopes[0]No propertiesvalues: ƒ values()arguments: (...)caller: (...)length: 0name: "values"__proto__: ƒ ()[[Scopes]]: Scopes[0]constructor: ƒ RTCStatsReport()size: (...)Symbol(Symbol.iterator): ƒ entries()arguments: (...)caller: (...)length: 0name: "entries"__proto__: ƒ ()apply: ƒ apply()arguments: (...)bind: ƒ bind()call: ƒ call()caller: (...)constructor: ƒ Function()length: 0name: ""toString: ƒ toString()Symbol(Symbol.hasInstance): ƒ [Symbol.hasInstance]()get arguments: ƒ ()set arguments: ƒ ()get caller: ƒ ()set caller: ƒ ()__proto__: Object[[FunctionLocation]]: <unknown>[[Scopes]]: Scopes[0][[Scopes]]: Scopes[0]Symbol(Symbol.toStringTag): "RTCStatsReport"get size: ƒ size()arguments: (...)caller: (...)length: 0name: "get size"__proto__: ƒ ()[[Scopes]]: Scopes[0]No properties__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()

2 : client1 call publication.getStats()
actual:
peercall.html:138 []0: RTCStatsReportsize: 9__proto__: RTCStatsReportentries: ƒ entries()forEach: ƒ forEach()get: ƒ ()has: ƒ has()keys: ƒ keys()values: ƒ values()constructor: ƒ RTCStatsReport()size: (...)Symbol(Symbol.iterator): ƒ entries()Symbol(Symbol.toStringTag): "RTCStatsReport"get size: ƒ size()__proto__: Object1: RTCStatsReportsize: 9__proto__: RTCStatsReportlength: 2__proto__: Array(0)concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}__proto__: Object

**Comment by jianjunz** [comment]
What you get is an RTCStatsReport with size 69. I guess it's detail enough.

**Comment by zhangyihui1** [comment]
I can not get video codec in RTCStatsReport

**Comment by jianjunz** [comment]
Please refer to https://w3c.github.io/webrtc-stats/ for WebRTC stats APIs.
