### ISSUE TITLE
The parameter Owt.Base.VideoTrackConstraints.frameRate does not work

### ISSUE THREAD

**Issue by zhenqi522** [open-webrtc-toolkit/owt-client-javascript#96]
Create mediaStream with options as following:
{"audio":{"source":"mic"},"video":{"source":"camera","resolution":{"width":640,"height":480},"framRate":25}}

**Comment by jianjunz** [comment]
`framRate` should be `frameRate`.

**Comment by zhenqi522** [comment]
frameRate works well. Close it.
